daos-stack/raft

src/raft_log.c
src/raft_server.c
tests/test_server.c

log_append_entry() passes caller's raft_entry_t to log_offer. If the
log_offer implementation sets the data buffer to different value,
caller's raft_entry_t gets modified as a side effect. This is
error-prone as callers are usually responsible for freeing the data
buffer with such a log_offer implementation. This patch passes the
raft_entry_t in the log to log_offer instead. Also, ety in
raft_recv_entry() is no longer required.

DAOS-279 log: Avoid changing caller input entry

---

include/raft_private.h
src/raft_server.c
tests/test_server.c

When a leader learns of a newer term and steps down, it should discard
current_leader. Otherwise, a client request may be rejected with
RAFT_ERR_NOT_LEADER and a hint pointing to this replica itself!
For simplicity, this patche follows the Raft paper to discard
current_leader whenever current_term changes. And, when receiving an AE
with an up-to-date term, a server always updates current_leader, as this
information is absolute, even if the previous entry doesn't match.
This patch also fixes a test that has previously been failing due to
incorrect node IDs.

DAOS-279 server: Discard current_leader when term changes

---

include/raft_private.h
src/raft_server.c
src/raft_server_properties.c
tests/test_server.c

If raft_become_candidate() assigns a negative value e (i.e.,
-election_timeout < e < 0) to timeout_elapsed, and if this replica
successfully becomes the leader, then this leader won't send heartbeats
for request_timeout - e milliseconds. This may be longer than
election_timeout and cause an unnecessary leadership change.
This patch zeroes timeout_elapsed in raft_become_leader(), randomizes
election timeouts in [election_timeout, 2 * election_timeout), and fixes
raft_recv_appendentries() to avoid zeroing timeout_elapsed if the AE
request has an older term.

DAOS-279 server: Zero timeout_elapsed for leaders

---

include/raft.h
include/raft_log.h
include/raft_private.h
src/raft_log.c
src/raft_server.c
tests/test_log.c
tests/test_server.c
tests/test_snapshotting.c

Support appending multiple entries to the end of the log.
Increase capacity of the log buffer exponentially by a factor
of two at a time, enough to ensure that there is enough to
append the given number of entries.
Also eliminated memcpy loop; instead call memcpy at the most
twice for copying existing entries to the newly allocated buffer.

DAOS-1021 log: Support batch offering

---

include/raft.h
include/raft_private.h
src/raft_log.c
src/raft_server.c
tests/test_log.c
tests/test_server.c

Support for deleting multiple entries from the tail of the log 
starting from the youngest entry. This order is important in
order to backtrack transitions to the state machine for correctly
restoring the state right before the oldest entry that is deleted.
Also, remove the redundant field 'back' used to track log entries.

DAOS-1046 log: Support batch popping

---

.gitignore

To avoid leaving the daos submodule dirty when running raft
tests
Signed-off-by: Jeff Olivier <jeffrey.v.olivier@intel.com>

DAOS-1197 test: Add files created by testing to .gitignore

---

Makefile
src/raft_server.c

It's not good coding practice to use the same name for temporaries and adding -Wshadow enables some optimization in macros (such as D_DEBUG in DAOS).  Also, since we build raft using the SConscript with DAOS settings, these warnings block DAOS from adding -Wshadow to fix and prevent its own issues.

DAOS-1333 build: Add -Wshadow to raft build

---

Makefile

Currently the Makefile recompiles object files only if the
corresponding source file has changed. We have run into a scenario
where a type definition was updated in a header causing different
object files to end up with multiple definitions of that same type
and resulting in memory corruption / segfaults.
Ideally, recompilation should occur only when an included header file
changes. But the simpler approach is to force recompilation when any
of the header files have changed; this works well for small projects.

DAOS-1876 build: Regenerate object files if headers change

---

include/raft.h
include/raft_private.h
src/raft_node.c
src/raft_server.c
tests/test_node.c
tests/test_server.c

Instead of using flags for tracking the status of a node, it can be
interpreted from the most recent log entries affecting a node.  Making
repeated changes to the flags and keeping track of them proves to be
error prone when there are a series of membership changes. This
solution also renders a lot of code redundant, e.g. in raft_offer_log
and raft_pop_log and allows for a more elegant implementation.

DAOS-1627 raft: Membership Changes

---

tests/test_server.c

A raft unit test fails with a segmentation fault because the local
stack variable of 'raft_entry_t' type is not being initialized. It may
happen that the 'type' field ends up with a value from the enumeration
'raft_logtype_e' and gets incorrectly processed by Raft as a change in
the membership, which leads to the segfault.

DAOS-2177 raft: Unit test fails in CI

---

include/raft.h
include/raft_private.h
src/raft_node.c
src/raft_server.c
src/raft_server_properties.c

Passing around pointers to raft_node_t objects and referencing them
all over the code results in errors and crashes due to dangling
pointers when nodes are removed. It is safer to use the node ID to
look up a node from the server's node list.
In the future, it would be ideal to introduce reference counting and
thread safety to Raft as a whole and the node list in particular.

DAOS-2181 raft: Avoid passing raft_node_t pointers around

---

Makefile

Some version of git requires master to be passed on the git pull
command line when fetching CLinkedListQueue
Signed-off-by: Johann Lombardi <johann.lombardi@intel.com>

DAOS-4023 raft: fix build issue when pulling CLinkedListQueue

---

tests/test_log.c

Fixing some entirely unimportant log object resource leaks in test_log.c since they are technically still leaks and they show up in DAOS's coverity static analysis
Signed-off-by: Byron Marohn <byron.marohn@intel.com>

Fix test_log log object resource leaks

---

src/raft_server.c

Signed-off-by: Bruno Faccini <bruno.faccini@intel.com>

DAOS-4328 raft: fix missing va_end() identified by Coverity

---

include/raft.h
include/raft_private.h
packaging/Makefile_distro_vars.mk
packaging/Makefile_packaging.mk
raft.spec

Move raft_election_start() function signature from private to public
header file. For DAOS use particularly in rdb/raft testing.
Signed-off-by: Kenneth Cain <kenneth.c.cain@intel.com>

DAOS-1742 raft: expose raft_election_start() function

---

Makefile-rpm.mk
debian/changelog
include/raft.h
include/raft_log.h
include/raft_private.h
include/raft_types.h
packaging/Makefile_packaging.mk
raft.spec
src/raft_log.c
src/raft_node.c
src/raft_server.c
src/raft_server_properties.c
tests/test_log.c
tests/test_scenario.c
tests/test_server.c
tests/test_snapshotting.c

Current 31-bit log indices are insufficient for production deployments.
This patch, based on upstream commit 2343e58b by Yossi Gottlieb, changes
both the log index type and the term type to long int.
Additionally, packaging changes from Brian Murrell are incorporated.

DAOS-2423 log: Use 63-bit indices and terms

---

debian/changelog
packaging/Makefile_packaging.mk
raft.spec
src/raft_server.c
tests/test_server.c

This patch fixes the following issues found by Coverity:
- Due to my recent "63-bit indices and terms" change, print formats
for indices and terms should be changed from "%d" to "%ld".
- What appears to be a copy-paste error in test_server.c.

DAOS-5731 misc: Fix Coverity issues

---

tests/log_fuzzer.py

Description: Fix the warning/errors raised by python bandit check (similar to pylint with security-check)
modified: raft/tests/log_fuzzer.py
Signed-off-by: Ding Ho <ding-hwa.ho@intel.com>

DAOS-5044-test: Fix python bandit errors on log_fuzzer.py

---

debian/changelog
packaging/Makefile_packaging.mk
packaging/rpm_chrootbuild
raft.spec
tests/test_server.c

Assert the returned pointer from raft_get_entry_from_idx() is non-NULL.
Signed-off-by: Kenneth Cain <kenneth.c.cain@intel.com>

Coverity fix test_server: raft_get_entry_from_idx return val

---

src/raft_server.c
tests/test_server.c

When a server receives a RequestVote request, if it has already voted
for this candidate in the same term, the server should grant this
repeated RequestVote.

DAOS-6833 server: Grant repeated RequestVotes

---

include/raft.h
include/raft_private.h
src/raft_server.c
src/raft_server_properties.c
tests/test_server.c

Add the Pre-Vote phase (§4.2.3, §9.6) before a candidate increments the
term, in order to prevent an isolated server from disrupting an existing
leader when the isolation ends.
A prevote field is added to both msg_requestvote_t and
msg_requestvote_response_t. Users may need to make code changes,
depending on how they transfer these messages.
The Pre-Vote phase is implemented as a substate, determined by
raft_server_private_t.prevote, in RAFT_STATE_CANDIDATE. A candidate
first enters the Pre-Vote phase (raft_server_private_t.prevote == 1),
requesting "prevotes". It's called a prevoting candidate in a few
places. If this candidate wins the Pre-Vote phase, it becomes a
"prevoted" candidate (raft_server_private_t.prevote == 0), requesting
(normal) votes.
A prevote request is evaluated against …

DAOS-6833 server: Add Pre-Vote

---

src/raft_server.c
tests/test_server.c

35d1029 clears leader_id after the Pre-Vote phase. That is too late,
because incoming RequestVote requests will be rejected during a minimum
election timeout from the beginning of the election, by the leader
aliveness check in raft_recv_requestvote. The leader_id should be
cleared as soon as a candidate resets timeout_elapsed.

DAOS-8023 server: Clear leader_id before prevote

---

debian/changelog
packaging/Dockerfile.centos.7
packaging/Dockerfile.coverity
packaging/Dockerfile.mockbuild
packaging/Dockerfile.ubuntu.20.04
packaging/Makefile_distro_vars.mk
packaging/Makefile_packaging.mk
packaging/rpm_chrootbuild
raft.spec
src/raft_server.c

raft_recv_installsnapshot_response returns immediately if the whole
snapshot has not yet been transferred completely. This causes next chunk
to be sent after an unnecessary request_timeout. The function should
instead continue the execution, skip the node state update, and see if
there is a new chunk to send immediately.

DAOS-7721 server: Fix IS performance

---

debian/changelog
include/raft.h
include/raft_private.h
packaging/Dockerfile.mockbuild
packaging/Makefile
packaging/Makefile_distro_vars.mk
packaging/Makefile_packaging.mk
packaging/rpm_chrootbuild
raft.spec
src/raft_server.c
tests/test_server.c

An optimization in raft_periodic lets a node who is the only voting node
in its local configuration become a leader without any election. No
persistent term or vote update is involved.
This behavior violates some Raft rules. Consider a two-node
configuration, C = {S1, S2}, where S1 is a follower in term 1 ("F1") and
S2 is a leader in term 1 ("L1"):
S1 (F1): [C]
S2 (L1): [C]
Both S1 and S2 have voted for S2 in term 1. Then, S2 is removed,
resulting in a new configuration, D = {S1}. Before S2 receives a reply
from S1 indicating that S1 has D:
S1 (F1): [C, D]
S2 (L1): [C, D]
S1 may become a leader in term 1 through the optimization, because it is
the only voting node in D, it doesn't increment the term, and it doesn't
go through any election. Before S2 commits D and steps down, the two …

DAOS-2054 server: Always go through elections

---

README.rst
include/raft.h
include/raft_log.h
include/raft_private.h
src/raft_log.c
src/raft_node.c
src/raft_server.c
src/raft_server_properties.c
tests/test_log.c
tests/test_node.c
tests/test_server.c

(The core change here may be of no interest to the upstream.)
Unfortunately, daos ends up needing to support re-adding a node with its
previous ID, which does not work properly with our algorithm and is not
supported by the upstream algorithm too. While daos will avoid reusing
node IDs eventually, it needs to provide compatiblity for existing
persistent raft state. This patch therefore reverts to the upstream
algorithm but drops the troublemaking logic that tracks the last applied
membership, which is not used by daos. The resulting algorithm is based
on the following principles:
- raft only tracks the active membership; the user shall track the
last applied membership for snapshotting purposes. (Tracking both
using the same set of raft_node_t objects in raft proves to be
complex. The …

DAOS-9326 server: Fix membership changes

---

src/raft_server.c

This fix is cherry-picked from the upstream.

Raft server's nodes vector is not freed when raft_free is invoked

---

debian/changelog
packaging/Dockerfile.mockbuild
packaging/Dockerfile.ubuntu.20.04
packaging/Makefile_packaging.mk
packaging/debian_chrootbuild
packaging/rpm_chrootbuild
raft.spec
src/raft_server.c
tests/test_server.c

A failure of the following assertion in raft_recv_requestvote was
observed:
assert(!raft_is_leader(me_) &&
(vr->prevote || !raft_is_candidate(me_)));
At the time, this server was very unlikely a leader. So it must be a
candidate granting a non-prevote RV request. Since a candidate votes for
itself only when becoming a _prevoted_ candidate, the server must be a
_prevoting_ candidate. This patch fixes the assertion to allow such a
valid case.
Related, raft_become_prevoted_candidate clears me->prevote too early. If
the raft_set_current_term call or the raft_vote_for_nodeid call returns
an error, the server is left as a prevoted candidate, but hasn't voted
for itself. If a non-prevote RV request comes in, the server may grant
the vote and fail the assertion above. This patch changes …

DAOS-10249 server: Fix RV assertion failures

---

src/raft_server.c
tests/test_server.c

If the request_timeout is misconfigured to be equal to or greater than election_timeout, it can lead to a situation where the leader receives a request vote from a precandidate, triggering an assertion in the code.
https://github.com/daos-stack/raft/blob/3d20556a08fc21deb6899104ad817d0a6e8e7af4/src/raft_server.c#L633
However, this issue may not be a critical error because the configuration of the Raft protocol is not normal.
Config the request_timeout to equal election_timeout. When the leader calls raft_periodic, it may cause `me->timeout_elapsed` to be equal to `me->election_timeout`, which can cause the condition check in the code to fail, and can further trigger the above assertion:
https://github.com/daos-stack/raft/blob/3d20556a08fc21deb6899104ad817d0a6e8e7af4/src/raft_server.c#L610- …

Reject request vote if self is leader

---

include/raft.h
include/raft_private.h
src/raft_node.c
src/raft_server.c
src/raft_server_properties.c
tests/test_server.c

This patch implements two features:
- Leadership leases (aka leases) for leaders to reduce RPCs sent just to verify leaderships. A leadership lease is a promise by a follower that it will not grant any new vote until a certain time, referred to as the lease expiration time. If a leader has valid leases, that is, leases that have not expired, from a majority of the voting nodes, then it may assume that no other leader could have committed any new entries behind its back.
- Voluntarily stepping down for leaders who are unable to maintain leases from a majority of the voting nodes. Clients who already know about this leader will then start a new leader search, rather than stick with this leader who is unable to commit any entries.
The library API sees the following changes:
- New lease field …

DAOS-12944 server: Track leadership leases

---

README.rst
debian/changelog
include/raft.h
include/raft_private.h
include/raft_types.h
raft.spec
src/raft_node.c
src/raft_server.c
src/raft_server_properties.c
tests/test_log.c
tests/test_scenario.c
tests/test_server.c
tests/test_snapshotting.c

Currently, the library implements the election timer using the time duration parameter msec_elapsed of raft_periodic. While this avoids introducing clocks into the library and eases testing, reasoning precisely about time becomes harder. For example, consider the following events on a follower:
Time  Event
10  raft_periodic(...)
15  raft_recv_appendentries(...)
// This call sets timeout_elapsed to 0.
20  raft_periodic(..., 20 - 10 /* msec_elapsed */)
// The actual time elapsed since the
// raft_recv_appendentries call is 20 - 15,
// rather than 20 - 10.
The election timer is _effectively_ reset by the raft_periodic call at time 10, instead of the raft_recv_appendentries call at time 15. When we implement leadership leases based on election timers, the lease granted by this follower …

DAOS-2424 server: Introduce raft_time_t

---

include/raft.h
packaging/Dockerfile.mockbuild
packaging/Makefile_packaging.mk
packaging/rpm_chrootbuild
src/raft_server.c

Add a new callback, get_rand, to raft_cbs_t, so that a user can choose his preferred pseudo-random number generator (PRNG). For instance, one can maintain his own PRNG instance in user_data (or elsewhere), to avoid consuming numbers from the default, global PRNG instance (e.g., the instance behind rand(3), which a library shall not seed).

DAOS-15120 include: Add get_rand to raft_cbs_t

---

debian/changelog
include/raft.h
packaging/ccache-stats.patch
packaging/get_base_branch
raft.spec
src/raft_server.c

Add a new level parameter to raft_cbs_t.log, so that we will be able to
enable the logging of errors and certain low-frequency messages without
being flooded by high-frequency messages from AEs.

DAOS-13965 include: Add logging levels

---

tests/log_fuzzer.py

distutils is deprecated, to be removed in python 3.12. Use the built-in shutil library instead.

DAOS-13130: replace distutils with shutil
